from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_
from app.core.database import get_db
from app.core.security import get_current_user
from app.models.user import User
from app.models.document import Document
from app.models.study import Summary, Quiz, Flashcard
from app.schemas.study import (
    SummaryRequest, SummaryResponse,
    QuizRequest, QuizResponse, QuizSubmitRequest, QuizResultResponse,
    FlashcardRequest, FlashcardItem, FlashcardListResponse
)
from app.services.study_service import (
    generate_document_summary,
    generate_document_quiz,
    generate_document_flashcards
)

router = APIRouter(prefix="/study", tags=["AI Study Tools"])


# ==========================================
# SUMMARIES
# ==========================================

@router.post("/summaries", response_model=SummaryResponse, status_code=status.HTTP_201_CREATED)
async def create_summary(
    request: SummaryRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Generate an AI executive summary, key concepts, and terminology from a study document."""
    # Verify document ownership
    doc_stmt = select(Document).where(and_(Document.id == request.document_id, Document.user_id == current_user.id))
    doc_res = await db.execute(doc_stmt)
    if not doc_res.scalar_one_or_none():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found.")

    summary = await generate_document_summary(
        document_id=request.document_id,
        user_id=current_user.id,
        focus_area=request.focus_area or "Comprehensive",
        db=db
    )
    return summary


@router.get("/summaries", response_model=List[SummaryResponse])
async def list_summaries(
    document_id: Optional[str] = None,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """List all generated summaries for the user."""
    stmt = select(Summary).where(Summary.user_id == current_user.id).order_by(Summary.created_at.desc())
    if document_id:
        stmt = stmt.where(Summary.document_id == document_id)
    result = await db.execute(stmt)
    return result.scalars().all()


@router.get("/summaries/{summary_id}", response_model=SummaryResponse)
async def get_summary(
    summary_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get single summary by ID."""
    stmt = select(Summary).where(and_(Summary.id == summary_id, Summary.user_id == current_user.id))
    result = await db.execute(stmt)
    summary = result.scalar_one_or_none()
    if not summary:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Summary not found.")
    return summary


# ==========================================
# QUIZZES
# ==========================================

@router.post("/quizzes", response_model=QuizResponse, status_code=status.HTTP_201_CREATED)
async def create_quiz(
    request: QuizRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Generate multiple-choice quiz questions from an indexed study document."""
    doc_stmt = select(Document).where(and_(Document.id == request.document_id, Document.user_id == current_user.id))
    doc_res = await db.execute(doc_stmt)
    if not doc_res.scalar_one_or_none():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found.")

    quiz = await generate_document_quiz(
        document_id=request.document_id,
        user_id=current_user.id,
        num_questions=request.num_questions,
        difficulty=request.difficulty,
        title=request.title,
        db=db
    )
    return quiz


@router.get("/quizzes", response_model=List[QuizResponse])
async def list_quizzes(
    document_id: Optional[str] = None,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """List all quizzes generated by the user."""
    stmt = select(Quiz).where(Quiz.user_id == current_user.id).order_by(Quiz.created_at.desc())
    if document_id:
        stmt = stmt.where(Quiz.document_id == document_id)
    result = await db.execute(stmt)
    return result.scalars().all()


@router.get("/quizzes/{quiz_id}", response_model=QuizResponse)
async def get_quiz(
    quiz_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get single quiz details and questions."""
    stmt = select(Quiz).where(and_(Quiz.id == quiz_id, Quiz.user_id == current_user.id))
    result = await db.execute(stmt)
    quiz = result.scalar_one_or_none()
    if not quiz:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Quiz not found.")
    return quiz


@router.post("/quizzes/{quiz_id}/submit", response_model=QuizResultResponse)
async def submit_quiz(
    quiz_id: str,
    submission: QuizSubmitRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Submit quiz answers, grade in real-time, and return score & detailed answer explanations."""
    stmt = select(Quiz).where(and_(Quiz.id == quiz_id, Quiz.user_id == current_user.id))
    result = await db.execute(stmt)
    quiz = result.scalar_one_or_none()
    if not quiz:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Quiz not found.")

    answers_map = {a.question_id: a.selected_option for a in submission.answers}
    correct_count = 0
    details = []

    for q in quiz.questions:
        q_id = q.get("id")
        correct_ans = q.get("correct_answer")
        user_ans = answers_map.get(q_id, -1)
        is_correct = (user_ans == correct_ans)
        
        if is_correct:
            correct_count += 1

        details.append({
            "question_id": q_id,
            "question": q.get("question"),
            "options": q.get("options", []),
            "selected_option": user_ans,
            "correct_option": correct_ans,
            "is_correct": is_correct,
            "explanation": q.get("explanation", "")
        })

    total = len(quiz.questions) or 1
    score_pct = round((correct_count / total) * 100.0, 1)

    if score_pct >= 90:
        feedback = "Outstanding! You have thoroughly mastered these core concepts."
    elif score_pct >= 70:
        feedback = "Great work! Review the explanations for any missed questions to solidify your understanding."
    elif score_pct >= 50:
        feedback = "Good effort. Consider re-reading the highlighted chapters and asking the AI Chat for clarifications."
    else:
        feedback = "Keep practicing. We recommend reviewing the generated summary and flashcards before retrying."

    return {
        "quiz_id": quiz_id,
        "total_questions": total,
        "correct_count": correct_count,
        "score_percentage": score_pct,
        "feedback": feedback,
        "details": details
    }


# ==========================================
# FLASHCARDS
# ==========================================

@router.post("/flashcards", response_model=List[FlashcardItem], status_code=status.HTTP_201_CREATED)
async def create_flashcards(
    request: FlashcardRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Generate high-yield study flashcards from an indexed document."""
    doc_stmt = select(Document).where(and_(Document.id == request.document_id, Document.user_id == current_user.id))
    doc_res = await db.execute(doc_stmt)
    if not doc_res.scalar_one_or_none():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found.")

    flashcards = await generate_document_flashcards(
        document_id=request.document_id,
        user_id=current_user.id,
        num_cards=request.num_cards,
        category=request.category or "Key Concepts",
        db=db
    )
    return flashcards


@router.get("/flashcards", response_model=List[FlashcardItem])
async def list_flashcards(
    document_id: Optional[str] = None,
    category: Optional[str] = None,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """List all flashcards for the user."""
    stmt = select(Flashcard).where(Flashcard.user_id == current_user.id).order_by(Flashcard.created_at.desc())
    if document_id:
        stmt = stmt.where(Flashcard.document_id == document_id)
    if category:
        stmt = stmt.where(Flashcard.category == category)
    result = await db.execute(stmt)
    return result.scalars().all()


@router.delete("/flashcards/{flashcard_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_flashcard(
    flashcard_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Delete a flashcard."""
    stmt = select(Flashcard).where(and_(Flashcard.id == flashcard_id, Flashcard.user_id == current_user.id))
    result = await db.execute(stmt)
    fc = result.scalar_one_or_none()
    if not fc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Flashcard not found.")
    await db.delete(fc)
    await db.commit()
    return None
